# Generated by Django 3.0.1 on 2020-01-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20191226_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_last_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(default='Please enter customer email', max_length=250),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_fname',
            field=models.CharField(default='Please enter customer first name', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_lname',
            field=models.CharField(default='Please enter customer last name', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_balance',
            field=models.CharField(default='Please enter account balance', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_name',
            field=models.CharField(default='Please enter account name', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_no',
            field=models.CharField(default='Please enter account number', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('checking', 'CHECKING'), ('savings', 'SAVINGS'), ('credit', 'CREDIT')], default=('checking', 'CHECKING'), max_length=200),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_location',
            field=models.CharField(default='Please enter branch location', max_length=200),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_name',
            field=models.CharField(default='Please enter branch name', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount_due',
            field=models.CharField(default='Please enter amount due', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_due',
            field=models.CharField(default='Please enter payment due date', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='loan_balance',
            field=models.CharField(default='Please enter loan balance', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='loan_type',
            field=models.CharField(choices=[('student', 'STUDENT'), ('home', 'HOME'), ('car', 'CAR')], default=('student', 'STUDENT'), max_length=200),
        ),
    ]
