# Generated by Django 3.0.1 on 2019-12-27 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branche',
            new_name='Branch',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='branche_location',
            new_name='branch_location',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='branche_name',
            new_name='branch_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_fname',
            new_name='customer_first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_lname',
            new_name='customer_last_name',
        ),
    ]
