# Generated by Django 2.2.7 on 2020-01-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20200106_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_fname',
            new_name='customer_first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_lname',
            new_name='customer_last_name',
        ),
    ]
