# Generated by Django 2.2.7 on 2020-01-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20200107_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Checking', 'CHECKING'), ('Savings', 'SAVINGS'), ('Credit', 'CREDIT')], default=('Checking', 'CHECKING'), max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(default='Please enter member email', max_length=250),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_first_name',
            field=models.CharField(default='Please enter member first name', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_last_name',
            field=models.CharField(default='Please enter member last name', max_length=200),
        ),
    ]
